// SPDX-License-Identifier: Apache-2.0

package com.digitalpebble.spruce;

import org.apache.spark.SparkIllegalArgumentException;
import org.apache.spark.sql.Row;
import org.apache.spark.sql.types.DataType;
import org.apache.spark.sql.types.StructType;

/**
 * Abstraction for columns. These can be either generated by the EnrichmentModules or coming from CUR reports.
 **/
public abstract class Column {

    private final String label;
    private final DataType type;

    // Single-entry cache: avoids repeated HashMap lookups in StructType.fieldIndex().
    // Safe without synchronization because all rows in a Spark partition (and typically
    // an entire job) share the same StructType instance, and the worst-case race is a
    // redundant fieldIndex() call.
    private transient StructType cachedSchema;
    private transient int cachedIndex;

    Column(String l, DataType t) {
        label = l;
        type = t;
    }

    /**
     * Returns the label of the column e.g. line_item_line_item_type
     **/
    public String getLabel() {
        return label;
    }

    /**
     * Returns the type of the column e.g. StringType
     **/
    public DataType getType() {
        return type;
    }

    /**
     * Resolves and caches the field index for this column in the given row's schema.
     * Uses identity comparison on the schema for a fast-path cache hit.
     **/
    public int resolveIndex(Row r) {
        StructType schema = r.schema();
        if (schema == cachedSchema) {
            return cachedIndex;
        }
        int index = r.fieldIndex(this.label);
        cachedSchema = schema;
        cachedIndex = index;
        return index;
    }

    /**
     * Utility method to get the value for the column in the row
     **/
    public double getDouble(Row r) {
        return r.getDouble(resolveIndex(r));
    }


    /**
     * Utility method to get the value for the column in the row or null if it does not exist.
     * Returns null if the field is not defined in the schema and optional is set to true,
     * propagates an exception otherwise.
     **/
    public String getString(Row r, boolean optional) {
        try {
            return r.getString(resolveIndex(r));
        } catch (SparkIllegalArgumentException e) {
            if (optional) {
                return null;
            }
            throw e;
        }
    }

    /**
     * Utility method to get the value for the column in the row or null if it does not exist
     **/
    public String getString(Row r) {
        return getString(r, false);
    }

    /**
     * Utility method to get check that a value is non null
     **/
    public boolean isNullAt(Row r) {
        return r.isNullAt(resolveIndex(r));
    }
}

