// SPDX-License-Identifier: Apache-2.0

package com.digitalpebble.spruce;

import org.apache.spark.sql.Row;
import org.apache.spark.sql.types.DataType;
import org.apache.spark.sql.types.StructType;

/**
 * Abstraction for columns. These can be either generated by the EnrichmentModules or coming from CUR reports.
 * Serializable because modules hold their column bindings as instance fields and are shipped to
 * the Spark executors; the schema/index cache is transient and rebuilt there.
 **/
public abstract class Column implements java.io.Serializable {

    private final String label;
    private final DataType type;

    // Single-entry cache: avoids repeated HashMap lookups in StructType.fieldIndex().
    // Safe without synchronization because all rows in a Spark partition (and typically
    // an entire job) share the same StructType instance, and the worst-case race is a
    // redundant fieldIndex() call.
    private transient StructType cachedSchema;
    private transient int cachedIndex;

    Column(String l, DataType t) {
        label = l;
        type = t;
    }

    /**
     * Returns the label of the column e.g. line_item_line_item_type
     **/
    public String getLabel() {
        return label;
    }

    /**
     * Returns the type of the column e.g. StringType
     **/
    public DataType getType() {
        return type;
    }

    /**
     * Resolves and caches the field index for this column in the given row's schema.
     * Uses identity comparison on the schema for a fast-path cache hit.
     * Throws if the column is absent from the schema.
     **/
    public int resolveIndex(Row r) {
        int index = resolveIndex(r, true);
        if (index == -1) {
            // throws the informative Spark exception listing the available fields
            return r.fieldIndex(this.label);
        }
        return index;
    }

    /**
     * Same as {@link #resolveIndex(Row)} but returns -1 when {@code optional} is true and the
     * column is absent from the schema. Misses are cached like hits, so probing for a column a
     * report does not carry (e.g. {@code resource_tags}) does not cost an exception per row.
     **/
    public int resolveIndex(Row r, boolean optional) {
        StructType schema = r.schema();
        if (schema != cachedSchema) {
            scala.Option<Object> index = schema.getFieldIndex(this.label);
            cachedIndex = index.isDefined() ? (Integer) index.get() : -1;
            cachedSchema = schema;
        }
        if (cachedIndex == -1 && !optional) {
            return r.fieldIndex(this.label);
        }
        return cachedIndex;
    }
}

